machine learning teaser
X , y , linear regression y = a1*x1 + a2*x2 + a3

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.DataFrame([[100,70,30],
[120,80,40],
[150,100,50],
[180,120,60],
[200,130,70]],columns = ['selling_price','cost_price','profit'])

In [ ]:
df.head()

selling_price  cost_price  profit
0            100          70      30
1            120          80      40
2            150         100      50
3            180         120      60
4            200         130      70

In [ ]:
X = df[['selling_price','cost_price']]
X

selling_price  cost_price
0            100          70
1            120          80
2            150         100
3            180         120
4            200         130

In [ ]:
y = df[['profit']]
y

profit
0      30
1      40
2      50
3      60
4      70

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X,y)

LinearRegression()

In [ ]:
model.coef_

array([[ 1., -1.]])

In [ ]:
model.intercept_

array([-4.26325641e-14])

In [ ]:
model.predict([[300,200]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[100.]])

In [ ]:
!pip install numpy

In [ ]:
!pip install pandas

In [ ]:
model2 = PolynomialRegression()

In [ ]:
model2.fit(X,y)

In [ ]:
model2.coef_