In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
a[1:4]

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b

In [ ]:
b[:,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
np.sum(b,axis=0)
np.sum(b,axis=1)

In [ ]:
d = b.reshape(b.size)

In [ ]:
b.reshape(b.size).shape

(6,)

In [ ]:
d .reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d .reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
d .reshape((-1,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
d .reshape((-1,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
d .reshape((-1,3))

array([[1, 2, 3],
       [4, 5, 6]])

**Boolean Array as Masks**

In [ ]:
x = np.arange(-3,5)
x

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
x % 2 == 1

array([ True, False,  True, False,  True, False,  True, False])

In [ ]:
x[x % 2 == 1]

array([-3, -1,  1,  3])

**3-D Array**

In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

In [ ]:
c[0,:,:]
c[1,:,:]

**Types of Data**


1.   Qualitative

*   Ordinal
*   Nomial


2.   Quantitative


*   Continous
*   Discrete





**Numerical Data**

Used for Quantitative Measurements


*   Discrete Data (Specific Value)

    Ex -> Number of Student in a class
*   Continuous Data (Range)

    Ex -> temperature, Height

**Categorical Data**


*   Nominal Data

    Ex -> Types of fruits
*   Ordinal Data

    Ex -> Education levels, Customers satisfaction ratings

