In [19]:
!pip install numpy
import numpy as np
np.array([0])

array([0])

In [ ]:
arr0d = np.array(1)
arr0d

array(1)

In [ ]:
arr0d.ndim

0

In [ ]:
arr1d = np.array([1,2,3])
arr1d

array([1, 2, 3])

In [ ]:
arr1d.dtype

dtype('int64')

In [ ]:
arr1d.shape

(3,)

In [ ]:
arr0d.shape

()

In [ ]:
arr1d.size

3

In [ ]:
np.__version__

'1.25.2'

In [ ]:
arr1d = np.arange(1,10)
arr1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [ ]:
import time
start_time = time.time()

a = [i for i in range(1000000)]
b = [i for i in range(1000000)]

result = [a[i] + b[i] for i in range(1000000)]
end_time = time.time()
print(start_time,end_time,end_time - start_time)

1709557863.8389895 1709557864.2684588 0.42946934700012207


In [ ]:
import time
start_time = time.time()

a = np.array(1000000)
b = np.array(1000000)

result = a+b
end_time = time.time()
print(start_time,end_time,end_time - start_time)

1709557685.7168307 1709557685.7170737 0.0002429485321044922


In [ ]:
a = np.ones(5)
a,a.dtype

(array([1., 1., 1., 1., 1.]), dtype('float64'))

In [ ]:
a = np.ones(5,dtype = 'int64')
a,a.dtype

(array([1, 1, 1, 1, 1]), dtype('int64'))

In [ ]:
x = np.arange(1,5)
x

array([1, 2, 3, 4])

In [ ]:
np.mean(x)

2.5

In [ ]:
np.median(x)

2.5

In [ ]:
np.min(x),np.max(x)

(1, 4)

In [ ]:
np.sum(x)

10

In [ ]:
zr_ar = np.zeros(3)
zr_ar

array([0., 0., 0.])

1. Mean is affected by outlier whereas median is robust to an outlier
2. Median is affected by Number of outliers

In [ ]:
salaries1 = np.array([30000,24000,60000])

In [ ]:
salaries2 = np.array([30000,24000,60000,100000,2000000]) #outliears

In [ ]:
np.mean(salaries1)

38000.0

In [ ]:
np.mean(salaries2)

442800.0

In [ ]:
np.median(salaries1)

30000.0

In [ ]:
np.median(salaries2)

60000.0

In [ ]:
# DATABASE 1
data1 = np.array([1,2,3,4,5])
m1 = np.mean(data1)
med1 = np.median(data1)

# DATABASE 2
data2 = np.array([3,3,3,3,3])
m2 = np.mean(data2)
med2 = np.median(data2)

print("Mean : ",m1)
print("Median : ",med1)
print("Mean : ",m2)
print("Median : ",med2)

Mean :  3.0
Median :  3.0
Mean :  3.0
Median :  3.0


Deviation
data1 -> 3 +- 1.414
data2 -> 3

**Moments of Data**

In [ ]:
arr = np.array([10,15,20,25,30])

In [ ]:
q2  = np.percentile(arr,50)
q2

20.0

In [ ]:
q1  = np.percentile(arr,25)
q1

15.0

In [ ]:
q3  = np.percentile(arr,75)
q3

25.0

In [ ]:
iqr = q3 - q1
iqr

10.0

**Five Number Summary :**
1. np.min()
2. np.percentile(arr,25)
3. np.percentile(arr,50)
4. np.percentile(arr,75)
5. np.max(arr)

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('president_heights.csv')
df.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

In [ ]:
type(df)

In [5]:
arr = df['height(cm)'].head()
arr

0    189
1    170
2    189
3    163
4    183
Name: height(cm), dtype: int64

In [8]:
arr = df['height(cm)'].values
arr

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 168, 170, 178, 182, 180,
       183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188,
       188, 182, 185, 191, 182])

In [14]:
print(arr)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185 191 182]


In [15]:
type(arr)

numpy.ndarray

In [16]:
print('array(',arr,')')

array( [189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185 191 182] )


In [17]:
type(arr)

numpy.ndarray

Avereage Height Of president

In [ ]:
np.mean(arr)

180.04545454545453

In [24]:
arr.mean()

180.04545454545453

In [25]:
arr.std()

6.983599441335736

In [26]:
arr.var()

48.7706611570248