In [ ]:
import numpy as np
"Running Fine"

'Running Fine'

Empty arraay and Full array

In [ ]:
np.empty((5,2))
np.full((5,2),0)
np.diag([1,2,3])

array([[4.69196364e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [6.89754732e-310, 3.79227302e+179],
       [4.99026597e+174, 6.25408009e-091],
       [3.15762825e-033, 6.89763205e-310]])

In [ ]:
np.full((100,),1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.eye(2,dtype=np.int64)

array([[1, 0],
       [0, 1]])

In [ ]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [ ]:
np.zeros((2,3),dtype='int64')

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
a1 = np.array([1,2,3,4])
np.any(a1 == 1)
np.all(a1==1)

False

Trignometric Function

In [ ]:
angle1 = np.array([0,90,180])
np.sin(angle1)
np.cos(angle1)

array([ 1.        , -0.44807362, -0.59846007])

Exponential and Log function

In [ ]:
ar1 = np.array([0,1])
np.exp(ar1)
np.log(ar1)

<ipython-input-33-5d32a94baf06>:3: RuntimeWarning: divide by zero encountered in log
  np.log(ar)


array([-inf,   0.])

Random functiom

In [ ]:
np.random.rand(3,3)
np.random.randint(10,size=(3,3))

array([[8, 5, 1],
       [0, 5, 5],
       [1, 9, 9]])

Boolean Masks

In [ ]:
ar2 = np.arange(-3,5)
ar2 > 0
ar2[ar2>0] # MASK FILTER

array([1, 2, 3, 4])

## Task to Find Promoters , Detractor and NPS Score From given File Survey.txt

In [ ]:
a = np.loadtxt('/content/survey.txt')
detractor = a[a <= 6]
promoter = a[a >= 9]
passive = a[(a>6) & (a <9)]
print(detractor,passive,promoter)
print(len(detractor),len(promoter))


In [ ]:
tot = a.size
nps = (detractor.size/tot)*100 - (promoter.size/tot)*100
print(nps)

-23.73607540702657


In [ ]:
nps_min = 0/tot*100 - tot/tot*100
nps_max = tot/tot*100 - 0/tot*100
print(nps_min,nps_max)

-100.0 100.0


In [ ]:
np.isnan(a)

array([False, False, False, ..., False, False, False])